version:      0.0.1

safe:         false
auto:         false
server:       false

baseurl:      http://engineering.spanishdict.com/
liveurl:      http://engineering.spanishdict.com
analytics:    TODO
disqus:       TODO
github:       https://github.com/spanishdict/engineering.spanishdict.com
title:        SpanishDict Engineering
subtitle:     Engineering at the world's largest Spanish learning website.
keywords:     ['SpanishDict', 'spanish', 'engineering']

source:       .
destination:  ./_site
exclude:      ["404.md", "Rakefile", "node_modules", "_styl"]

future:       true
lsi:          false
pygments:     true
markdown:     maruku
permalink:    date
